#!/usr/bin/env bash

set -e

if ! command -v pandoc &> /dev/null
then
    brew install pandoc   # Install pandoc using Homebrew
fi

pandoc ./script/terms/terms.md -f markdown-smart -t rtf -o ./script/terms/terms.rtf --standalone
